parameters:
  kapitan:
    dependencies:
      - type: helm
        output_path: dependencies/promtheus-pushgateway/helmcharts/promtheus-pushgateway
        source: https://prometheus-community.github.io/helm-charts
        version: ${promtheus_pushgateway:charts:promtheus-pushgateway}
        chart_name: promtheus-pushgateway
    compile:
      - input_paths:
          - prometheus-pushgateway/component/app.jsonnet
        input_type: jsonnet
        output_path: apps/
      - input_paths:
          - prometheus-pushgateway/component/main.jsonnet
        input_type: jsonnet
        output_path: prometheus-pushgateway/
      - output_path: prometheus-pushgateway/10_prometheus_pushgateway_helmchart
        input_type: helm
        output_type: yaml
        input_paths:
          - prometheus-pushgateway/helmcharts/prometheus-pushgateway
        helm_values: ${prometheus_pushgateway:helmValues}
        helm_params:
          release_name: traefik
          namespace: '${prometheus_pushgateway:namespace}'
